### ISSUE TITLE
User profile and settings 

### ISSUE THREAD

**Issue by botirk38** [botirk38/StartupPlanner#1]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't easily update my personal information or manage my account settings. Currently, there is no dedicated section for users to view and edit their profiles, change their passwords, or adjust their notification preferences. This makes it inconvenient to maintain an updated account and manage settings effectively.

**Describe the solution you'd like**
I would like a comprehensive user profile and settings feature where users can:
1. View and edit their personal information (name, email, phone number, etc.).
2. Change their password and manage login credentials.
3. Adjust notification preferences (email notifications, SMS alerts, etc.).
4. Upload and change profile pictures.
5. Manage connected accounts (e.g., linking social media or other service accounts).
6. View account activity and login history for security purposes.
7. Delete or deactivate their account if needed.

**Describe alternatives you've considered**
An alternative solution could be integrating these settings into various sections of the existing application rather than a dedicated profile section. However, this might lead to a fragmented user experience where users need to navigate multiple areas to manage their account settings.:

This feature will enhance user experience by providing a centralized location for managing account settings, thereby making the application more intuitive and user-friendly.

**Comment by botirkhaltaev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User profile and settings](https://trello.com/c/B0CLhQ7p/13-user-profile-and-settings)
